dist: trusty

language: go

node_js:
  - "node"

go:
  - 1.13

matrix:
  include:
    - os: osx
    - os: linux
    - os: windows

install:
  - go mod download

script:
  - go version
  - go env
  - echo $PWD
  - cd server
  - echo $PWD
  - go build

branches:
  only:
    - master
