version: "3.7"
services:
  bbs-go-server:
    image: mlogclub/bbs-go-server
    container_name: bbs-go-server
    networks:
      - bbsgo
    build:
      target: application
      context: server
    depends_on:
      - start_dependencies
    environment:
      - APP_ENV
    restart: on-failure
    volumes:
      - "./data:/data/"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - bbs-go-mysql
    command: 127.0.0.1:3306

  bbs-go-site:
    image: mlogclub/bbs-go-site
    container_name: bbs-go-site
    build:
      target: application
      context: site
    depends_on:
      - bbs-go-server
    environment:
      - APP_ENV
    restart: on-failure

  bbs-go-mysql:
    image: "mysql:5.7"
    container_name: bbs-go-mysql
    networks:
      - bbsgo
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ".docker-compose/mysql/db/conf.d:/etc/mysql/conf.d"
      - ".docker-compose/mysql/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

networks:
  bbsgo:

volumes:
  bbs-go-server: {}
  bbs-go-site: {}
  bbs-go-mysql: {}
