dist: trusty
sudo: required

language: 
  - go

node_js:
  - "node"

go:
  - master

matrix:
  include:
    - os: osx
    - os: linux
    - os: windows

install:
  - go mod download

script:
  - go run build

branches:
  only:
    - master
